# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 300)
        Form.setMinimumSize(QtCore.QSize(700, 300))
        Form.setMaximumSize(QtCore.QSize(700, 300))
        self.msg_edit = QtWidgets.QPlainTextEdit(Form)
        self.msg_edit.setGeometry(QtCore.QRect(380, 50, 291, 171))
        self.msg_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.msg_edit.setPlainText("")
        self.msg_edit.setObjectName("msg_edit")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 190, 241, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.layoutWidget)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.password_button = QtWidgets.QPushButton(self.layoutWidget)
        self.password_button.setObjectName("password_button")
        self.horizontalLayout.addWidget(self.password_button)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 50, 315, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.user_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.user_edit.setMinimumSize(QtCore.QSize(194, 0))
        self.user_edit.setObjectName("user_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_edit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pwd_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pwd_edit.setObjectName("pwd_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pwd_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2.raise_()
        self.pwd_edit.raise_()
        self.label.raise_()
        self.user_edit.raise_()

        self.retranslateUi(Form)
        self.login_button.clicked.connect(self.msg_edit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_button.setText(_translate("Form", "登录"))
        self.password_button.setText(_translate("Form", "清空"))
        self.label_2.setText(_translate("Form", "密  码："))
        self.label.setText(_translate("Form", "用户名："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
